# -*- coding: utf-8 -*-
"""Turn the translated chunks under ``itp_work/kr`` into ``vmp_system_text.py``.

The opening patch keeps its Korean in a hand-written module; the rest of the
executable is 793 strings and was translated in parallel, so it is generated
instead.  Every entry is checked against the field it overwrites before it is
written out, and the Japanese is carried in a comment so the table can be read.
"""

from __future__ import annotations

import io
import json
from pathlib import Path

import pycdlib

from falcom_font import FalcomFont
from korean_slots import build_slot_map, make_encoder

ISO = Path("Vantage Master Portable (1.01).iso")
BOOT = "/PSP_GAME/SYSDIR/BOOT.BIN"
TODO = Path("itp_work/exe_todo.json")
KOREAN = Path("itp_work/kr")
OUT = Path("vmp_system_text.py")

HEADER = '''# -*- coding: utf-8 -*-
"""Korean text for the rest of Vantage Master Portable's executable.

Generated by ``build_system_text.py`` from the chunks under ``itp_work/kr``; the
opening's own strings live in ``vmp_opening_text.py``.  Every entry is
``(label, offset, korean)`` and is written over the Japanese in place, so each
one has been checked to fit its field.  The Japanese is quoted above each entry
for review -- edit the Korean here and the change survives a rebuild, because
the generator only ever adds offsets that are missing.
"""

from __future__ import annotations

SYSTEM_TEXT: list[tuple[str, int, str]] = [
'''


def label_for(japanese: str) -> str:
    # Split on CR as well as LF: a raw CR inside the quoted label would end the
    # string literal, and 62 of these fields break their lines with CR.
    head = japanese.replace("\r", "\n").split("\n", 1)[0]
    return head[:24].replace('"', "'")


def main() -> None:
    with ISO.open("rb") as handle:
        iso = pycdlib.PyCdlib()
        iso.open_fp(handle)
        try:
            buffer = io.BytesIO()
            iso.get_file_from_iso_fp(buffer, iso_path=BOOT)
            boot = buffer.getvalue()
        finally:
            iso.close()

    todo = {entry["off"]: entry for entry in json.loads(TODO.read_text(encoding="utf-8"))}
    korean: dict[int, str] = {}
    for path in sorted(KOREAN.glob("*.json")):
        for key, value in json.loads(path.read_text(encoding="utf-8")).items():
            korean[int(str(key), 0)] = value

    font = FalcomFont(Path("pspfont.dat").read_bytes())
    encode = make_encoder(build_slot_map(font))
    lines: list[str] = []
    skipped: list[tuple[int, str]] = []
    for offset in sorted(korean):
        entry = todo.get(offset)
        if entry is None:
            skipped.append((offset, "not in the work list"))
            continue
        text = korean[offset]
        try:
            size = len(encode(text))
        except Exception as error:  # noqa: BLE001 - report and drop, never ship
            skipped.append((offset, str(error)))
            continue
        capacity = entry["len"] + entry["slack"]
        if size > capacity:
            skipped.append((offset, f"{size} > {capacity} bytes"))
            continue
        # A raw CR in a comment ends the line and spills the rest into code:
        # 62 of these fields break their lines with CR rather than LF.
        japanese = entry["jp"].replace(chr(10), chr(92) + "n").replace(chr(13), chr(92) + "r")
        lines.append(f'    # {japanese}\n    ("{label_for(entry["jp"])}", 0x{offset:X}, {text!r}),\n')

    OUT.write_text(HEADER + "".join(lines) + "]\n", encoding="utf-8")
    print(f"wrote {OUT} with {len(lines)} entries; dropped {len(skipped)}")
    for offset, why in skipped[:20]:
        print(f"  0x{offset:06X}: {why}")


if __name__ == "__main__":
    main()
