"""Build the Korean opening patch for Vantage Master Portable.

Three things go into the ISO:

* ``system/pspfont.dat`` and the compressed copy inside ``data/pack/init0.dat``
  with 2,350 Hangul rasters written into the glyph records the game actually
  looks up (JIS level 2 and the IBM/NEC extension blocks -- level-1 kanji are
  left alone so untranslated Japanese still reads).
* the opening text in ``BOOT.BIN`` / ``EBOOT.BIN``, encoded to the Shift-JIS
  codes of those very records.
* the three opening event scripts and their packed copies.

``jis2utf.bin`` and ``utf2jis.bin`` are deliberately left untouched: they are
code-conversion tables, not part of the glyph lookup, and the earlier attempt
to fix the mapping through them is what produced ``젯늠`` instead of ``저는``.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import shutil
from pathlib import Path

import pycdlib

import pack_textures
import patch_event_scripts
import patch_map_names
import patch_scripts
import quiz_text as quiz
import ui_texture_text as ui
import vmp_opening_text as text

try:  # generated by build_system_text.py; absent until it has been run
    import vmp_system_text
except ModuleNotFoundError:  # pragma: no cover - the opening patch alone still builds
    vmp_system_text = None
from falcom_font import FalcomFont
from korean_slots import build_slot_map, make_encoder
from patch_packed_pspfont import PACK_PSPFONT_RECORD, ed7_decompress, parse_pack_record
from patch_ui_textures import patch_texture

BOOT_PATH = "/PSP_GAME/SYSDIR/BOOT.BIN"
EBOOT_PATH = "/PSP_GAME/SYSDIR/EBOOT.BIN"
LOOSE_FONT_PATH = "/PSP_GAME/USRDIR/system/pspfont.dat"
PACK_FONT_PATH = "/PSP_GAME/USRDIR/data/pack/init0.dat"
ASM_PACK_PATH = "/PSP_GAME/USRDIR/data/pack/asm.dat"
MAP_SCRIPT_DIR = "/PSP_GAME/USRDIR/data/map/_asm"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_iso_file(iso_path: Path, iso_file: str) -> bytes:
    with iso_path.open("rb") as iso_fp:
        iso = pycdlib.PyCdlib()
        iso.open_fp(iso_fp)
        try:
            with iso.open_file_from_iso(iso_path=iso_file) as file_fp:
                return file_fp.read()
        finally:
            iso.close()


def field_source(data: bytes, offset: int, padding: bool = False) -> tuple[str, int]:
    """Return the CP932 text at ``offset`` and how many bytes may replace it.

    By default a translation may only be as long as the Japanese it replaces.
    The NUL bytes that follow look like linker alignment and buying them back
    fits another 127 strings, but they are not ours: the build that used them
    is the one where the scenario world map drew no map, no icons and no
    panel, and putting the executable back to the opening's 212 fields fixed
    it.  Something in that padding is read, so ``padding=True`` stays off.
    """
    end = data.find(bytes(1), offset)
    if end < 0:
        raise ValueError(f"no NUL terminator after the field at 0x{offset:X}")
    if not padding:
        return data[offset:end].decode("cp932"), end - offset
    last = end
    while last + 1 < len(data) and data[last + 1] == 0:
        last += 1
    return data[offset:end].decode("cp932"), last - offset


def card_name(japanese: str) -> str:
    """Pull the Latin card name out of 'あなたが選んだのは X のカード。...'."""
    head = japanese.split("\n", 1)[0]
    start = head.index("のは ") + 3
    end = head.index(" のカード")
    return head[start:end]


def build_fields(
    boot: bytes, system_text: bool = True, text_range: tuple[int, int] | None = None
) -> list[tuple[str, int, str]]:
    """Every (label, offset, korean) the opening patch writes."""
    fields: list[tuple[str, int, str]] = []
    fields += text.MODE_SELECT
    fields += text.NAME_ENTRY
    fields += text.SELECTION_PROMPTS
    fields += text.APTITUDES
    fields += text.PROLOGUE
    fields += text.STARTING_ITEMS
    fields += text.TUTORIAL
    fields += text.SYSTEM_AND_SETUP

    for label, offset, meaning in text.CARDS:
        japanese, _capacity = field_source(boot, offset)
        fields.append(
            (label, offset, text.CARD_TEMPLATE.format(name=card_name(japanese), meaning=meaning))
        )

    # Everything outside the opening -- the system menu, the tutorial, item and
    # Netear descriptions, the battle help -- lives in a generated table.
    if system_text and vmp_system_text is not None:
        claimed = {offset for _label, offset, _korean in fields}
        # main() appends the class introductions after this function returns.
        claimed |= {offset for offset, _name, _poem in text.CLASS_INTROS}
        chosen = [entry for entry in vmp_system_text.SYSTEM_TEXT if entry[1] not in claimed]
        if text_range is not None:
            low, high = text_range
            chosen = [entry for entry in chosen if low <= entry[1] < high]
        fields += chosen
    return fields


def class_intro(encode, capacity: int, name: str, poem: str) -> str:
    """Pick the longest class template that still fits the field."""
    for template in text.CLASS_TEMPLATES:
        candidate = template.format(cls=name, poem=poem)
        if len(encode(candidate)) <= capacity:
            return candidate
    raise ValueError(f"no class template fits {name} in {capacity} bytes")


def patch_fields(boot: bytes, fields: list[tuple[str, int, str]], encode, optional: set[int] | None = None):
    """Write each translation over its field, padding the rest with NULs."""
    result = bytearray(boot)
    report: list[str] = []
    skipped: list[str] = []
    seen: dict[int, str] = {}
    for label, offset, korean in fields:
        if offset in seen:
            raise ValueError(f"offset 0x{offset:X} is claimed by both {seen[offset]!r} and {label!r}")
        seen[offset] = label
        japanese, capacity = field_source(boot, offset)
        encoded = encode(korean)
        if len(encoded) > capacity:
            if optional and offset in optional:
                skipped.append(f"{label} @0x{offset:X}: {len(encoded)} > {capacity} bytes")
                continue
            raise ValueError(
                f"{label} at 0x{offset:X}: {len(encoded)} bytes of Korean do not fit "
                f"in {capacity} bytes -- {korean!r}"
            )
        result[offset : offset + capacity] = encoded.ljust(capacity, b"\0")
        report.append(
            f"{label} @0x{offset:X} {capacity}->{len(encoded)} bytes\n"
            f"    JP: {japanese}\n"
            f"    KR: {korean}"
        )
    if skipped:
        report.append(f"skipped {len(skipped)} fields that no longer fit:")
        report += [f"    {line}" for line in skipped]
    return bytes(result), report


def patch_event_file(data: bytes, specs: list[tuple[str, str]], encode):
    """Replace whole NUL-terminated strings inside an event script."""
    result = bytearray(data)
    report: list[str] = []
    for source, target in specs:
        source_bytes = source.encode("cp932")
        encoded = encode(target)
        search_from = 0
        matches = 0
        while True:
            offset = result.find(source_bytes, search_from)
            if offset < 0:
                break
            end = offset + len(source_bytes)
            if (offset > 0 and result[offset - 1] != 0) or result[end] != 0:
                search_from = offset + 1
                continue
            capacity = end - offset
            if len(encoded) > capacity:
                raise ValueError(
                    f"event translation too long for {source!r}: {len(encoded)} > {capacity}"
                )
            result[offset:end] = encoded.ljust(capacity, b"\0")
            report.append(f"0x{offset:X}: {source} -> {target}")
            matches += 1
            search_from = end + 1
        if matches == 0:
            raise ValueError(f"event source string not found: {source!r}")
    return bytes(result), report


def verify_font_pair(input_iso: Path, loose: bytes, packed: bytes) -> None:
    original_loose = read_iso_file(input_iso, LOOSE_FONT_PATH)
    original_packed = read_iso_file(input_iso, PACK_FONT_PATH)
    if len(loose) != len(original_loose):
        raise ValueError(f"loose font is {len(loose)} bytes, ISO expects {len(original_loose)}")
    if len(packed) != len(original_packed):
        raise ValueError(f"packed archive is {len(packed)} bytes, ISO expects {len(original_packed)}")
    name, data_offset, compressed_size, _uncompressed, _flags = parse_pack_record(
        packed, PACK_PSPFONT_RECORD
    )
    if name != "pspfont.dat":
        raise ValueError(f"packed record {PACK_PSPFONT_RECORD} is {name!r}, not pspfont.dat")
    recovered = ed7_decompress(packed[data_offset : data_offset + compressed_size])
    if recovered != loose:
        raise ValueError("the packed font does not decompress to the loose font")


def replace_files_in_place(input_iso: Path, output_iso: Path, replacements: dict[str, bytes]) -> None:
    if input_iso.resolve() == output_iso.resolve():
        raise ValueError("refusing to modify the input ISO in place")
    if output_iso.exists():
        output_iso.unlink()
    shutil.copy2(input_iso, output_iso)
    with output_iso.open("r+b") as iso_fp:
        iso = pycdlib.PyCdlib()
        iso.open_fp(iso_fp)
        try:
            for iso_file, replacement in replacements.items():
                with iso.open_file_from_iso(iso_path=iso_file) as file_fp:
                    original = file_fp.read()
                if len(original) != len(replacement):
                    raise ValueError(
                        f"{iso_file}: replacement is {len(replacement)} bytes, "
                        f"original is {len(original)}"
                    )
                iso.modify_file_in_place(
                    io.BytesIO(replacement), len(replacement), iso_path=iso_file
                )
        finally:
            iso.close()
        iso_fp.flush()


def grow_asm_pack(output_iso: Path, patched_asm: bytes) -> None:
    """Write the longer asm.dat into the sectors it already owns.

    pycdlib will only write a file back at its original length, and the Korean
    names cost 203 bytes.  The file is 92,534 bytes inside a 94,208-byte
    allocation, so nothing has to move: only the length in its ISO9660
    directory record changes.
    """
    with output_iso.open("rb") as handle:
        iso = pycdlib.PyCdlib()
        iso.open_fp(handle)
        try:
            record = next(
                child
                for child in iso.list_children(iso_path=pack_textures.PACK_DIR)
                if not (child.is_dot() or child.is_dotdot())
                and child.file_identifier().decode().split(";")[0] == "asm.dat"
            )
            extent, length = record.extent_location(), record.get_data_length()
        finally:
            iso.close()
    data = bytearray(output_iso.read_bytes())
    patch_map_names.grow_in_place(data, extent, length, "asm.dat", patched_asm)
    output_iso.write_bytes(bytes(data))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=Path("Vantage Master Portable (1.01).iso"))
    parser.add_argument(
        "--output", type=Path, default=Path("Vantage Master Portable (Korean opening).iso")
    )
    parser.add_argument("--font", type=Path, default=Path("korean_font_slotmapped/pspfont_korean.dat"))
    parser.add_argument(
        "--packed-font", type=Path, default=Path("korean_font_slotmapped/init0_korean.dat")
    )
    parser.add_argument("--textures", type=Path, default=Path("itp_work/patched"))
    parser.add_argument(
        "--no-dialogue",
        action="store_true",
        help="leave the event scripts alone (the Korean dialogue is opt-out, not opt-in)",
    )
    parser.add_argument("--report-dir", type=Path, default=Path("korean_opening_build"))
    parser.add_argument(
        "--system-text-range",
        metavar="LO:HI",
        help=(
            "patch only the generated fields whose offset is in [LO, HI), as hex. "
            "One of these 793 strings stops the scenario world map drawing its "
            "map, icons and panel, and halving the range is how it gets found."
        ),
    )
    parser.add_argument(
        "--no-system-text",
        action="store_true",
        help=(
            "patch only the opening's own 212 fields, leaving the 793 generated "
            "ones out.  A bisecting switch: the world map screen draws no map, "
            "icons or panel, and this is the one change left that touches the "
            "executable."
        ),
    )
    parser.add_argument(
        "--map-names",
        action="store_true",
        help=(
            "also translate the 52 battle map names.  Off by default: the Korean "
            "names make asm.dat 203 bytes longer, which pushes unit._as past the "
            "length the file shipped with, and the scenario map list froze on the "
            "build that carried them."
        ),
    )
    args = parser.parse_args()

    loose_font = args.font.read_bytes()
    packed_font = args.packed_font.read_bytes()

    verify_font_pair(args.input, loose_font, packed_font)

    original_font = FalcomFont(read_iso_file(args.input, LOOSE_FONT_PATH))
    slot_map = build_slot_map(original_font)
    encode = make_encoder(slot_map)

    # The 52 battle map names are the first string in each map script, which the
    # ISO carries loose, inside asm.dat, and inside the asm.dat that init0.dat
    # bundles.  Rewriting them makes asm.dat 203 bytes longer, so init0.dat is
    # repacked around it -- there is room because the font member it already
    # carries is padded -- and asm.dat itself is grown into its own spare
    # sectors after the ISO is written.
    patched_asm: bytes | None = None
    map_scripts: dict[str, bytes] = {}
    if args.map_names:
        original_asm = read_iso_file(args.input, ASM_PACK_PATH)
        patched_asm, map_scripts = patch_map_names.patch_asm(original_asm, encode)
        packed_font = patch_map_names.patch_init0(packed_font, patched_asm)

    boot = read_iso_file(args.input, BOOT_PATH)
    eboot = read_iso_file(args.input, EBOOT_PATH)

    text_range = None
    if args.system_text_range:
        low, high = (int(part, 16) for part in args.system_text_range.split(":"))
        text_range = (low, high)
    fields = build_fields(boot, system_text=not args.no_system_text, text_range=text_range)
    for offset, name, poem in text.CLASS_INTROS:
        _japanese, capacity = field_source(boot, offset)
        fields.append((f"class {name}", offset, class_intro(encode, capacity, name, poem)))

    optional = {offset for _l, offset, _k in vmp_system_text.SYSTEM_TEXT} if vmp_system_text else set()
    patched_boot, field_report = patch_fields(boot, fields, encode, optional=optional)
    if len(eboot) < len(patched_boot):
        raise ValueError("EBOOT.BIN is smaller than the patched ELF")
    patched_eboot = patched_boot.ljust(len(eboot), b"\0")

    replacements: dict[str, bytes] = {
        BOOT_PATH: patched_boot,
        EBOOT_PATH: patched_eboot,
        LOOSE_FONT_PATH: loose_font,
        PACK_FONT_PATH: packed_font,
    }

    for member, plain in sorted(map_scripts.items()):
        replacements[f"{MAP_SCRIPT_DIR}/{member}"] = plain

    # The scenario dialogue: every translated line is written where it lies and
    # padded with spaces, so the scripts and the packs around them keep their
    # exact byte layout.  ``vmp_opening_text.EVENT_FILES`` is no longer used --
    # it padded with NULs, and these strings run back to back.
    event_report: list[str] = []
    if not args.no_dialogue:
        scripts, event_report, overruns = patch_event_scripts.build(args.input, encode)
        if overruns:
            raise ValueError(
                f"{len(overruns)} dialogue lines do not fit their field: "
                + " | ".join(overruns[:10])
            )
        replacements.update(scripts)

    # The map, unit and master scripts.  These carry the advice the HELP box
    # shows on the map-select screen, the master and class names, and each
    # master's profile -- everything the dialogue pass never reached.  Same
    # rule as the dialogue: each translation is padded to the bytes the
    # Japanese used, so the loose files keep their layout; and every member of
    # asm.dat is required to come back no larger than the stream it replaces,
    # so the pack keeps its length and the copy init0.dat stores verbatim can
    # be spliced straight back in.
    script_report: list[str] = []
    script_files, script_asm, script_report, script_trouble = patch_scripts.build(
        args.input, encode)
    if script_trouble:
        raise ValueError(
            f"{len(script_trouble)} scripts do not fit: " + " | ".join(script_trouble[:10]))
    if script_files:
        replacements.update(script_files)
        replacements[ASM_PACK_PATH] = script_asm
        packed_font = patch_scripts.splice_into_init0(packed_font, script_asm)
        replacements[PACK_FONT_PATH] = packed_font

    args.report_dir.mkdir(parents=True, exist_ok=True)
    texture_report: list[str] = []
    scratch = args.report_dir / "_texture_scratch.itp"
    for name, labels in ui.PATCHES.items():
        iso_file = f"{ui.ISO_DIR}/{name}.itp"
        original = read_iso_file(args.input, iso_file)
        prebuilt = args.textures / f"{name}.itp"
        if prebuilt.exists() and prebuilt.stat().st_size == len(original):
            # patch_ui_textures.py already rebuilt this atlas; re-compressing a
            # 512x512 texture here only risks running the build out of memory.
            padded = prebuilt.read_bytes()
            used = len(padded.rstrip(b"\0"))
        else:
            padded, exact, _image = patch_texture(original, labels, scratch)
            used = len(exact)
        replacements[iso_file] = padded
        texture_report.append(
            f"{iso_file}: {len(labels)} labels, {used} of {len(original)} bytes used"
        )
        texture_report += [
            f"    ({x},{y}) {w}x{h} -> {korean}" for x, y, w, h, korean in labels
        ]
    scratch.unlink(missing_ok=True)

    # The questionnaire atlases are always taken from patch_quiz_textures.py's
    # output: they are 512x512 and re-compressing them here is what ran the
    # build out of memory.
    for name, (paragraphs, _column, _pitch, options) in quiz.QUIZ.items():
        iso_file = f"{ui.ISO_DIR}/{name}.itp"
        original = read_iso_file(args.input, iso_file)
        prebuilt = args.textures / f"{name}.itp"
        if not prebuilt.exists() or prebuilt.stat().st_size != len(original):
            raise FileNotFoundError(
                f"run patch_quiz_textures.py first: {prebuilt} is missing or the wrong size"
            )
        replacements[iso_file] = prebuilt.read_bytes()
        texture_report.append(
            f"{iso_file}: {len(paragraphs)} paragraphs, {len(options)} option strips"
        )
        for _x, _y, _w, _h, lines in paragraphs:
            texture_report += [f"    {line}" for line in lines if line.strip()]
        texture_report += [f"    [{index}] {korean}" for index, korean in sorted(options.items())]

    # Everything else that has been rendered into itp_work/patched -- the 108
    # gallery pages, and whatever atlas is finished next.  A prebuilt file is
    # only taken when it is exactly the length the ISO shipped, because a pack
    # member may not move.
    extra = 0
    for prebuilt in sorted(args.textures.glob("*.itp")):
        iso_file = f"{ui.ISO_DIR}/{prebuilt.stem}.itp"
        if iso_file in replacements:
            continue
        try:
            original = read_iso_file(args.input, iso_file)
        except Exception:  # noqa: BLE001 - not a texture this ISO carries
            continue
        if prebuilt.stat().st_size != len(original):
            raise ValueError(
                f"{prebuilt} is {prebuilt.stat().st_size} bytes, the ISO holds {len(original)}"
            )
        replacements[iso_file] = prebuilt.read_bytes()
        extra += 1
    texture_report.append(f"prebuilt atlases taken from {args.textures}: {extra}")

    # The loose data/system copies are decoration: the loader reads these same
    # textures out of the pack archives, so every packed copy has to change too.
    patched_members = {
        iso_file.rsplit("/", 1)[1]: data
        for iso_file, data in replacements.items()
        if iso_file.startswith(f"{ui.ISO_DIR}/") and iso_file.endswith(".itp")
    }
    located = pack_textures.find_packs(args.input, set(patched_members))
    # The gallery, manual and battle-record atlases are in no pack at all -- the
    # loader reads those straight from data/system -- so an atlas without a
    # packed copy is normal.  The ones that DO have one must all be found,
    # because that copy is the one the game prefers.
    packed_names = {
        f"{name}.itp"
        for name in list(ui.PATCHES) + list(quiz.QUIZ)
        if name not in ui.LOOSE_ONLY
    }
    missing = packed_names - set(located)
    if missing:
        raise ValueError(f"these textures were not found in any pack: {sorted(missing)}")
    texture_report.append(
        f"atlases with no packed copy (loose only): "
        f"{len(set(patched_members) - set(located))}"
    )

    packs: dict[str, bytes] = {}
    for member, places in sorted(located.items()):
        for pack_name, record in places:
            iso_file = f"{pack_textures.PACK_DIR}/{pack_name}"
            # init0.dat already carries the Korean font at this point, so start
            # from whatever this build has produced for the pack, not the ISO.
            current = (
                packs.get(iso_file)
                or replacements.get(iso_file)
                or read_iso_file(args.input, iso_file)
            )
            packs[iso_file] = pack_textures.splice(current, record, patched_members[member])
        texture_report.append(
            f"{member}: spliced into {len(places)} pack(s): "
            + ", ".join(sorted(pack for pack, _ in places))
        )
    replacements.update(packs)

    (args.report_dir / "BOOT.BIN.patched").write_bytes(patched_boot)
    sample = list(slot_map.items())
    (args.report_dir / "opening_patch_report.txt").write_text(
        "Vantage Master Portable -- Korean opening patch\n"
        "===============================================\n"
        f"Font: {args.font} sha256={sha256(loose_font)}\n"
        f"Packed archive: {args.packed_font} sha256={sha256(packed_font)}\n"
        "Glyph lookup: index = range_base + (shift_jis_code - range_start), then the\n"
        "variable-width record at 0xC4 + index*4 (uint24 column offset, uint8 width).\n"
        f"Hangul slots: {len(slot_map)} records of 15 px in JIS level 2 and the IBM/NEC\n"
        "extension blocks; JIS level-1 kanji keep their Japanese glyphs.\n"
        "jis2utf.bin / utf2jis.bin: unchanged (not part of the glyph lookup).\n\n"
        "Slot samples\n------------\n"
        + "\n".join(
            f"{char} U+{ord(char):04X} -> SJIS 0x{code:04X} "
            f"(glyph {original_font.index_of(code)}, was "
            f"{bytes((code >> 8, code & 0xFF)).decode('cp932')})"
            for char, code in (sample[0], sample[1], sample[409], sample[1593], sample[-1])
        )
        + f"\n\nExecutable fields ({len(fields)})\n"
        + "-" * 30
        + "\n"
        + "\n".join(field_report)
        + f"\n\nEvent script fields ({len(event_report)})\n"
        + "-" * 30
        + "\n"
        + "\n".join(event_report)
        + f"\n\nMap, unit and master scripts ({len(script_report)})\n"
        + "-" * 30
        + "\n"
        + "\n".join(script_report)
        + "\n\nUI texture labels\n"
        + "-" * 30
        + "\n"
        + "\n".join(texture_report)
        + "\n",
        encoding="utf-8",
    )

    replace_files_in_place(args.input, args.output, replacements)
    if patched_asm is not None:
        grow_asm_pack(args.output, patched_asm)
    for iso_file, expected in replacements.items():
        if read_iso_file(args.output, iso_file) != expected:
            raise ValueError(f"verification failed for {iso_file}")

    print(f"Built {args.output} ({args.output.stat().st_size} bytes)")
    print(f"Executable fields patched: {len(fields)}")
    print(f"Event script strings patched: {len(event_report)}")
    print(f"Map/unit/master script files patched: {len(script_files)}")
    print(f"Report: {args.report_dir / 'opening_patch_report.txt'}")


if __name__ == "__main__":
    main()
